//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devart.AI.McpServer.Odbc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Devart.AI.McpServer.Odbc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manages the MCP Server configurations: list, add, edit, delete; with no subcommand, displays the configuration window.
        /// </summary>
        public static string CommandLine_CommandConfigOdbc {
            get {
                return ResourceManager.GetString("CommandLine_CommandConfigOdbc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devart AI MCP Server (ODBC).
        /// </summary>
        public static string CommandLine_RootCommand {
            get {
                return ResourceManager.GetString("CommandLine_RootCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either the &apos;dsn&apos; or the &apos;connection_string&apos; parameters must be present in the configuration file..
        /// </summary>
        public static string Common_ConfigFileDsnRequired {
            get {
                return ResourceManager.GetString("Common_ConfigFileDsnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparently, {0} is not installed. You can download the driver at {1}..
        /// </summary>
        public static string Connection_DriverNotInstalled {
            get {
                return ResourceManager.GetString("Connection_DriverNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ODBC driver is not supported. This server works with {0}. Check the driver specified in the data source. You can download the required driver at {1}..
        /// </summary>
        public static string Connection_UnsupportedDriver {
            get {
                return ResourceManager.GetString("Connection_UnsupportedDriver", resourceCulture);
            }
        }
    }
}
